[package]
name = "wascc-host"
version = "0.1.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"
homepage = "https://wascc.dev"
description = "WebAssembly Secure Capabilities Connector host runtime"
license = "Apache-2.0"
documentation = "https://docs.rs/wascc-host"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasi", "wascc"]
categories = ["wasm", "data-structures","command-line-utilities"]


[[bin]]
name = "wascchost"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.5.2"
crossbeam-channel = "0.4.0"
crossbeam = "0.7.3"
crossbeam-utils = "^0.7.0"
wapc = "0.1.0"
wascc-codec = "0.3.3"
wascap = "0.1.0"
prost = "0.5.0"
#bytes = "0.4.12"
log = "0.4.8"
env_logger = "0.7.1"
lazy_static = "1.4.0"
quicli = "0.4"
structopt = "0.3.5"
term-table = "1.2.0"
exitfailure = "0.5.1"
chrono-humanize = "0.0.11"
chrono = "0.4.10"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.43"