name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Build with Gantry+Manifest
      run: cargo build --verbose --features "manifest gantry bin"
    - name: Run tests Gantry+Manifest
      run: cargo test --verbose --features "manifest gantry bin"
    - name: Run tests (manifest only)
      run: cargo test --verbose --features "manifest"
    - name: Run tests (gantry only)
      run: cargo test --verbose --features "gantry"    
